import express from 'express';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { StrategyEngine, defaultConfig } from './strategy.js';
import { initDatabase, syncEngineToDatabase, getPerformance, getHistoricalEntries, databaseEnabled } from './database.js';

const __dirname=path.dirname(fileURLToPath(import.meta.url));
const app=express(), port=process.env.PORT||3000;
const TFS=['M1','M3'];
const engines=Object.fromEntries(TFS.map(tf=>[tf,new StrategyEngine({...defaultConfig,timeframe:tf})]));
const rollups={M3:null};
const BRIDGE_TOKEN=process.env.BRIDGE_TOKEN||'', TELEGRAM_BOT_TOKEN=process.env.TELEGRAM_BOT_TOKEN||'', TELEGRAM_CHAT_ID=process.env.TELEGRAM_CHAT_ID||'';
const TELEGRAM_NOTIFY_PENDING=String(process.env.TELEGRAM_NOTIFY_PENDING||'false').toLowerCase()==='true';
const mt5={lastSeen:null,lastCandle:null,lastTick:null,lastRealtimeTransition:null,symbol:'XAUUSD',bid:null,ask:null,serverTime:null};
const telegramMetrics={lastSentAt:null,lastApiMs:null,lastEvent:null,lastTimeframe:null};
app.use(express.json({limit:'4mb'})); app.use(express.static(path.join(__dirname,'..','public')));
let dbReady=false;
try { dbReady=await initDatabase(); if(dbReady) console.log('Trading database initialized'); else console.warn('Trading database disabled'); } catch(e){console.error('Trading database init failed:',e.message)}
let dbSyncTimer=null;
async function syncAllToDatabase(){if(!dbReady||!databaseEnabled())return false;await Promise.all(TFS.map(tf=>syncEngineToDatabase(tf,engines[tf])));return true}
function scheduleDbSync(){if(!dbReady||!databaseEnabled())return;if(dbSyncTimer)clearTimeout(dbSyncTimer);dbSyncTimer=setTimeout(()=>{dbSyncTimer=null;syncAllToDatabase().catch(e=>console.error('Database sync failed:',e.message))},300)}
const normTf=v=>{const s=String(v||'M1').toUpperCase().replace('MIN','M');if(['1','M1'].includes(s))return'M1';if(['3','M3'].includes(s))return'M3';throw new Error('timeframe must be M1 or M3')};
const normTime=v=>{const x=Number(v??Date.now());return x<1e12?x*1000:x};
const normCandle=c=>({time:normTime(c.time),open:Number(c.open),high:Number(c.high),low:Number(c.low),close:Number(c.close),volume:Number(c.volume??0)});
const fmt=v=>Number(v).toFixed(3), telegramReady=()=>Boolean(TELEGRAM_BOT_TOKEN&&TELEGRAM_CHAT_ID), mt5Connected=()=>Boolean(mt5.lastSeen&&Date.now()-mt5.lastSeen<90000);
function requireBridge(req,res){if(!BRIDGE_TOKEN){res.status(503).json({ok:false,error:'BRIDGE_TOKEN is not configured on server'});return false}const token=req.get('x-bridge-token')||req.query.token||'';if(token!==BRIDGE_TOKEN){res.status(401).json({ok:false,error:'invalid bridge token'});return false}return true}
async function sendTelegram(text,meta={}){if(!telegramReady())return false;const started=Date.now();try{const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:TELEGRAM_CHAT_ID,text,disable_web_page_preview:true})});const apiMs=Date.now()-started;if(!r.ok){console.error('Telegram send failed:',r.status,await r.text());return false}Object.assign(telegramMetrics,{lastSentAt:Date.now(),lastApiMs:apiMs,lastEvent:meta.event||'MESSAGE',lastTimeframe:meta.tf||null});console.log(`Telegram sent event=${telegramMetrics.lastEvent} tf=${telegramMetrics.lastTimeframe||'-'} apiMs=${apiMs}`);return true}catch(e){console.error('Telegram error:',e.message);return false}}
function tradeMap(e){return new Map(e.trades.map(t=>[t.id,{status:t.status,result:t.result,tpHits:[...t.tpHits]}]))} function pendingSet(e){return new Set(e.setups.filter(s=>s.status==='pending').map(s=>s.id))}
function entryMessage(tf,t){return[`${t.dir==='buy'?'🟢':'🔴'} ENTRY ${t.dir.toUpperCase()} ${engines[tf].config.symbol} ${tf}`,`Entry: ${fmt(t.entry)}`,`SL: ${fmt(t.sl)} (${Number(t.slPips).toFixed(1)} pips)`,`TP1: ${fmt(t.tps[0])}`,`TP2: ${fmt(t.tps[1])}`,`TP3: ${fmt(t.tps[2])}`,`TP4: ${fmt(t.tps[3])}`,'Method: Fresh OB + FVG',`Rule: Swing SL max ${engines[tf].config.maxSwingSlPips} pips`].join('\n')}
function tpMessage(tf,t,i){return[`✅ ${engines[tf].config.symbol} ${tf} ${t.dir.toUpperCase()} — TP${i+1} HIT`,`Entry: ${fmt(t.entry)}`,`TP${i+1}: ${fmt(t.tps[i])}`,'Status winrate utama: WIN'].join('\n')}
function slMessage(tf,t){return[`⛔ ${engines[tf].config.symbol} ${tf} ${t.dir.toUpperCase()} — SL HIT`,`Entry: ${fmt(t.entry)}`,`SL: ${fmt(t.sl)}`,t.tpHits?.[0]?'TP1 sudah tercapai sebelumnya — winrate utama tetap WIN':'TP1 belum tercapai — hasil utama LOSS'].join('\n')}
function pendingMessage(tf,s){return[`⏳ SETUP ${s.dir.toUpperCase()} ${engines[tf].config.symbol} ${tf}`,`Entry rencana: ${fmt(s.plannedEntry)}`,`FVG: ${fmt(s.fvgBottom)} - ${fmt(s.fvgTop)}`,'Status: PENDING — belum dihitung sampai Entry tersentuh'].join('\n')}
function dispatchTransitions(tf,beforeTrades,beforePending){const e=engines[tf];let transitions=0;for(const t of e.trades){const p=beforeTrades.get(t.id);if(!p){transitions++;void sendTelegram(entryMessage(tf,t),{event:'ENTRY',tf});continue}let highest=-1;for(let i=0;i<t.tpHits.length;i++)if(!p.tpHits[i]&&t.tpHits[i])highest=i;if(highest>=0){transitions++;void sendTelegram(tpMessage(tf,t,highest),{event:`TP${highest+1}`,tf})}if(p.status==='live'&&t.status==='closed'&&t.result==='SL'){transitions++;void sendTelegram(slMessage(tf,t),{event:'SL',tf})}}if(TELEGRAM_NOTIFY_PENDING)for(const s of e.setups)if(s.status==='pending'&&!beforePending.has(s.id)){transitions++;void sendTelegram(pendingMessage(tf,s),{event:'PENDING',tf})}return transitions}
function ingestEngine(tf,candle,notify=true){const e=engines[tf],bt=notify?tradeMap(e):null,bp=notify?pendingSet(e):null,r=e.ingest(candle);if(notify)dispatchTransitions(tf,bt,bp);return r}
function processRealtimeTick(price,time){let changed=false,transitions=0;for(const tf of TFS){const e=engines[tf],bt=tradeMap(e),bp=pendingSet(e),r=e.processTick({price,time});if(!r.changed)continue;changed=true;transitions+=dispatchTransitions(tf,bt,bp)}if(changed){mt5.lastRealtimeTransition=Date.now();scheduleDbSync()}return{changed,transitions}}
function rollupM1(c){const bucket=Math.floor(c.time/180000)*180000,cur=rollups.M3;if(!cur||cur.time!==bucket){const completed=cur?{...cur}:null;rollups.M3={time:bucket,open:c.open,high:c.high,low:c.low,close:c.close,volume:c.volume||0};return completed}cur.high=Math.max(cur.high,c.high);cur.low=Math.min(cur.low,c.low);cur.close=c.close;cur.volume+=c.volume||0;return null}
function ingestOne(tfRaw,candleRaw,autoAggregate=true,notify=true){const tf=normTf(tfRaw),c=normCandle(candleRaw),r=ingestEngine(tf,c,notify);if(tf==='M1'&&autoAggregate){const completed=rollupM1(c);if(completed)ingestEngine('M3',completed,notify)}return r}
function combinedSnapshot(){const timeframes=Object.fromEntries(TFS.map(tf=>[tf,engines[tf].snapshot()]));const histories=TFS.flatMap(tf=>timeframes[tf].history.map(x=>({...x,timeframe:tf}))).sort((a,b)=>(b.openedTime||0)-(a.openedTime||0)).slice(0,300);const signals=TFS.map(tf=>timeframes[tf].lastSignal).filter(Boolean).sort((a,b)=>(b.time||0)-(a.time||0));const wins=TFS.reduce((n,tf)=>n+timeframes[tf].stats.primary.wins,0),losses=TFS.reduce((n,tf)=>n+timeframes[tf].stats.primary.losses,0),resolved=wins+losses,confirmed=TFS.reduce((n,tf)=>n+timeframes[tf].stats.confirmedEntries,0);return{symbol:engines.M1.config.symbol,livePrice:mt5.bid??timeframes.M1.price,strategy:'Fresh OB + FVG | M1 + M3 | Hybrid Realtime Tick | Swing SL Max 50 pips | TP 1R-4R',hybridRealtime:true,timeframes,lastSignal:signals[0]||null,history:histories,database:{configured:databaseEnabled(),ready:dbReady},integrations:{mt5:{connected:mt5Connected(),hybridRealtime:true,lastSeen:mt5.lastSeen,lastCandle:mt5.lastCandle,lastTick:mt5.lastTick,lastRealtimeTransition:mt5.lastRealtimeTransition,symbol:mt5.symbol,bid:mt5.bid,ask:mt5.ask,serverTime:mt5.serverTime},telegram:{configured:telegramReady(),notifyPending:TELEGRAM_NOTIFY_PENDING,...telegramMetrics}},combined:{confirmedEntries:confirmed,totalTrades:confirmed,liveTrades:TFS.reduce((n,tf)=>n+timeframes[tf].stats.live,0),pending:TFS.reduce((n,tf)=>n+timeframes[tf].pending.length,0),skipped:TFS.reduce((n,tf)=>n+timeframes[tf].stats.skipped,0),overall:{wins,losses,resolved,winrate:resolved?+(wins/resolved*100).toFixed(1):0,rule:'M1 + M3 only. TP1 = WIN; SL sebelum TP1 = LOSS.'}}}}

// Daily setup report: isolated scheduler only; trading logic is untouched.
let lastDailyReportDate=null;
function jakartaClock(now=new Date()){const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Jakarta',year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',hourCycle:'h23'}).formatToParts(now);const get=t=>parts.find(p=>p.type===t)?.value;return{date:`${get('year')}-${get('month')}-${get('day')}`,hour:Number(get('hour')),minute:Number(get('minute'))}}
function dailySetupMessage(){const lines=['📊 DAILY SETUP REPORT — XAUUSD','Timeframe: M1 + M3','Method: Fresh OB + FVG',`Live price: ${Number.isFinite(Number(mt5.bid))?fmt(mt5.bid):'—'}`,''];for(const tf of TFS){const e=engines[tf],pending=e.setups.filter(s=>s.status==='pending');lines.push(`【${tf}】`);if(!pending.length){lines.push('Belum ada setup pending valid.');continue}for(const s of pending.slice(0,5)){lines.push(`${s.dir==='buy'?'🟢 BUY':'🔴 SELL'} | Entry ${fmt(s.plannedEntry)} | FVG ${fmt(s.fvgBottom)}-${fmt(s.fvgTop)}`)}}lines.push('','Setup akan tetap mengikuti validasi engine M1/M3 dan baru dihitung sebagai trade setelah entry tersentuh.');return lines.join('\n')}
async function sendDailySetupReport(source='SCHEDULE'){const ok=await sendTelegram(dailySetupMessage(),{event:'DAILY_SETUP'});console.log(`Daily setup report source=${source} status=${ok?'SENT':'FAILED'}`);return ok}
setInterval(()=>{const j=jakartaClock();if(j.hour===7&&j.minute<5&&lastDailyReportDate!==j.date){lastDailyReportDate=j.date;void sendDailySetupReport('07:00_WIB').then(ok=>{if(!ok)lastDailyReportDate=null})}},30000);
console.log('Daily setup Telegram scheduler active at 07:00 WIB');

app.get('/api/health',(_q,r)=>r.json({ok:true,service:'ai-trading-ob-fvg-mtf',timeframes:TFS,hybridRealtime:true,mt5Connected:mt5Connected(),telegramConfigured:telegramReady(),databaseConfigured:databaseEnabled(),databaseReady:dbReady,time:new Date().toISOString()}));
app.get('/api/status',(_q,r)=>r.json(combinedSnapshot()));app.get('/api/integrations',(_q,r)=>r.json(combinedSnapshot().integrations));
app.get('/api/performance',async(_q,r)=>{try{if(!dbReady)return r.status(503).json({error:'database not ready'});r.json(await getPerformance())}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/history',async(q,r)=>{try{if(!dbReady)return r.status(503).json({error:'database not ready'});const tf=q.query.timeframe?normTf(q.query.timeframe):null;r.json({history:await getHistoricalEntries({timeframe:tf,limit:q.query.limit||500}),database:true})}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/status/:tf',(q,r)=>{try{r.json(engines[normTf(q.params.tf)].snapshot())}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/config',(_q,r)=>r.json({shared:{...engines.M1.config,timeframe:undefined},timeframes:Object.fromEntries(TFS.map(tf=>[tf,engines[tf].config]))}));
app.post('/api/config',(q,r)=>{try{const patch={...(q.body||{})},only=patch.timeframe?normTf(patch.timeframe):null;delete patch.timeframe;(only?[only]:TFS).forEach(tf=>engines[tf].updateConfig({...patch,timeframe:tf}));r.json({ok:true,config:Object.fromEntries(TFS.map(tf=>[tf,engines[tf].config]))})}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/signals',(q,r)=>{try{const tf=q.query.timeframe?normTf(q.query.timeframe):null;if(tf)return r.json({timeframe:tf,lastSignal:engines[tf].lastSignal,history:engines[tf].snapshot().history,stats:engines[tf].stats()});const s=combinedSnapshot();r.json({lastSignal:s.lastSignal,history:s.history,overall:s.combined.overall,stats:Object.fromEntries(TFS.map(x=>[x,engines[x].stats()]))})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/candle',(q,r)=>{try{const b=q.body||{},c=b.candle||b;ingestOne(b.timeframe||c.timeframe||'M1',c,b.autoAggregate!==false,b.notify===true);scheduleDbSync();r.json(combinedSnapshot())}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/candles',(q,r)=>{try{const b=q.body||{},cs=Array.isArray(b)?b:b.candles;if(!Array.isArray(cs))return r.status(400).json({error:'candles array required'});for(const c of cs)ingestOne(c.timeframe||b.timeframe||'M1',c.candle||c,b.autoAggregate!==false,b.notify===true);scheduleDbSync();r.json(combinedSnapshot())}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/reset',(q,r)=>{try{if(q.body?.timeframe)engines[normTf(q.body.timeframe)].reset();else{TFS.forEach(tf=>engines[tf].reset());rollups.M3=null}r.json({ok:true,status:combinedSnapshot(),databasePreserved:true})}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/mt5/backfill',async(q,r)=>{if(!requireBridge(q,r))return;try{const b=q.body||{},cs=b.candles;if(!Array.isArray(cs))return r.status(400).json({ok:false,error:'candles array required'});const tf=b.timeframe||'M1';if(normTf(tf)!=='M1'&&b.autoAggregate!==false)return r.status(400).json({ok:false,error:'autoAggregate backfill must use M1 source only'});if(b.symbol){mt5.symbol=b.symbol;TFS.forEach(x=>engines[x].updateConfig({symbol:b.symbol,timeframe:x}))}for(const c of cs)ingestOne(c.timeframe||tf,c,b.autoAggregate!==false,false);mt5.lastSeen=Date.now();await syncAllToDatabase();r.json({ok:true,imported:cs.length,databaseSynced:dbReady,status:combinedSnapshot()})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.post('/api/mt5/tick',(q,r)=>{if(!requireBridge(q,r))return;try{const b=q.body||{};mt5.lastSeen=Date.now();mt5.lastTick=normTime(b.time??Date.now());mt5.serverTime=b.serverTime?normTime(b.serverTime):mt5.lastTick;mt5.symbol=b.symbol||mt5.symbol;mt5.bid=Number.isFinite(Number(b.bid))?Number(b.bid):mt5.bid;mt5.ask=Number.isFinite(Number(b.ask))?Number(b.ask):mt5.ask;const price=Number.isFinite(Number(mt5.bid))?Number(mt5.bid):Number(mt5.ask),realtime=Number.isFinite(price)?processRealtimeTick(price,mt5.lastTick):{changed:false,transitions:0};r.json({ok:true,mt5Connected:true,hybridRealtime:true,realtimeChanged:realtime.changed,transitions:realtime.transitions})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.post('/api/mt5/webhook',(q,r)=>{if(!requireBridge(q,r))return;try{const b=q.body||{},tf=b.timeframe||b.candle?.timeframe||'M1';if(b.symbol){mt5.symbol=b.symbol;TFS.forEach(x=>engines[x].updateConfig({symbol:b.symbol,timeframe:x}))}mt5.lastSeen=Date.now();const c=b.candle||b;mt5.lastCandle=normTime(c.time??Date.now());ingestOne(tf,c,b.autoAggregate!==false,true);scheduleDbSync();const s=combinedSnapshot();r.json({ok:true,signal:s.lastSignal,integrations:s.integrations,status:s})}catch(e){r.status(400).json({ok:false,error:e.message})}});
app.post('/api/telegram/test-ui',async(q,r)=>{if(!telegramReady())return r.status(409).json({ok:false,error:'Telegram is not configured on server.'});const ok=await sendTelegram(String(q.body?.message||'✅ AI Trading OB+FVG Telegram privat test berhasil.').trim().slice(0,500),{event:'TEST'});r.status(ok?200:502).json({ok,apiMs:telegramMetrics.lastApiMs})});
app.post('/api/telegram/test',async(q,r)=>{if(!requireBridge(q,r))return;if(!telegramReady())return r.status(409).json({ok:false,error:'Telegram is not configured.'});const ok=await sendTelegram(q.body?.message||'✅ AI Trading OB+FVG Telegram connected. M1 / M3 notifications are active.',{event:'TEST'});r.status(ok?200:502).json({ok,apiMs:telegramMetrics.lastApiMs})});
app.post('/api/telegram/daily-report-test',async(q,r)=>{if(!telegramReady())return r.status(409).json({ok:false,error:'Telegram is not configured.'});const ok=await sendDailySetupReport('MANUAL_TEST');r.status(ok?200:502).json({ok,apiMs:telegramMetrics.lastApiMs})});
app.use((_q,r)=>r.sendFile(path.join(__dirname,'..','public','index.html')));app.listen(port,()=>console.log(`AI Trading OB+FVG M1/M3 listening on :${port}`));
