import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// TP probabilities are injected into LIMIT commands at runtime from the same strategy estimator.
const serverPath = path.join(__dirname, 'server.js');
const marker = "app.post('/api/telegram/test',async(q,r)=>{";
const legacyMarker = "app.post('/api/telegram/test', async (req,res) => {";
const uiRoute = `app.post('/api/telegram/test-ui', async (req,res) => { if (!telegramReady()) return res.status(409).json({ok:false,error:'Telegram is not configured on server.'}); const raw=String(req.body?.message||'✅ AI Trading OB+FVG Telegram test berhasil.').trim(); const ok=await sendTelegram(raw.slice(0,500),{event:'TEST'}); res.status(ok?200:502).json({ok,apiMs:telegramMetrics.lastApiMs}); });\n`;
const dailyTestRoute = `app.post('/api/telegram/daily-test', async (_req,res) => { if (!telegramReady()) return res.status(409).json({ok:false,error:'Telegram is not configured on server.'}); const ok=await sendDailySetupReport('MANUAL_TEST'); res.status(ok?200:502).json({ok,event:'DAILY_SETUP',apiMs:telegramMetrics.lastApiMs}); });\n`;
let source=fs.readFileSync(serverPath,'utf8');
source=source.replace("import { StrategyEngine, defaultConfig } from './strategy.js';","import { StrategyEngine, defaultConfig, tpProbabilityEstimate } from './strategy.js';");
const routeMarker=source.includes(marker)?marker:legacyMarker;
if(!source.includes(routeMarker))throw new Error('Telegram route marker not found');
if(!source.includes("app.post('/api/telegram/test-ui'"))source=source.replace(routeMarker,uiRoute+routeMarker);
if(!source.includes("app.post('/api/telegram/daily-test'"))source=source.replace(routeMarker,dailyTestRoute+routeMarker);

source=source.replace("TELEGRAM_CHAT_ID=process.env.TELEGRAM_CHAT_ID||'';","TELEGRAM_CHAT_ID=process.env.TELEGRAM_CHAT_ID||'', TELEGRAM_GROUP_CHAT_ID=process.env.TELEGRAM_GROUP_CHAT_ID||'';");
const oldSend="async function sendTelegram(text,meta={}){if(!telegramReady())return false;const started=Date.now();try{const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:TELEGRAM_CHAT_ID,text,disable_web_page_preview:true})});const apiMs=Date.now()-started;if(!r.ok){console.error('Telegram send failed:',r.status,await r.text());return false}Object.assign(telegramMetrics,{lastSentAt:Date.now(),lastApiMs:apiMs,lastEvent:meta.event||'MESSAGE',lastTimeframe:meta.tf||null});console.log(`Telegram sent event=${telegramMetrics.lastEvent} tf=${telegramMetrics.lastTimeframe||'-'} apiMs=${apiMs}`);return true}catch(e){console.error('Telegram error:',e.message);return false}}";
const dualSend="async function sendTelegram(text,meta={}){if(!telegramReady())return false;const started=Date.now();const targets=(meta.privateOnly?[['PRIVATE',TELEGRAM_CHAT_ID]]:[['PRIVATE',TELEGRAM_CHAT_ID],['GROUP',TELEGRAM_GROUP_CHAT_ID]]).filter(([,id])=>Boolean(id));let allOk=true;try{for(const [label,chatId] of targets){const r=await fetch(`https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:chatId,text,disable_web_page_preview:true})});if(!r.ok){allOk=false;console.error(`Telegram ${label} send failed:`,r.status,await r.text())}else console.log(`Telegram destination=${label} delivered`)}const apiMs=Date.now()-started;Object.assign(telegramMetrics,{lastSentAt:allOk?Date.now():telegramMetrics.lastSentAt,lastApiMs:apiMs,lastEvent:meta.event||'MESSAGE',lastTimeframe:meta.tf||null});return allOk}catch(e){console.error('Telegram error:',e.message);return false}}";
if(!source.includes('TELEGRAM_GROUP_CHAT_ID'))throw new Error('Telegram group variable patch failed');
if(source.includes(oldSend))source=source.replace(oldSend,dualSend);

// Auto execution V2.2: broker-side first-touch LIMIT orders are armed while the Web AI setup is still PENDING.
// The legacy /api/mt5/commands route is intentionally left empty so V2.1 cannot misread LIMIT commands as market orders.
const autoExecPrelude=`
const AUTO_TRADE=String(process.env.AUTO_TRADE||'false').toLowerCase()==='true';
const mt5Exec={queue:[],seen:new Set(),acked:new Map(),limits:new Map(),lastPoll:null,lastAck:null};
async function persistExec(cmd,status='QUEUED'){if(!dbReady)return;try{await saveMt5ExecutionCommand(cmd,status)}catch(e){console.error('MT5 execution persist failed:',e.message)}}
async function persistAck(id,status,ticket,detail){if(!dbReady)return;try{await updateMt5ExecutionCommand(id,status,{ticket,detail})}catch(e){console.error('MT5 execution ack persist failed:',e.message)}}
async function recoverMt5ExecutionQueue(){if(!dbReady||!AUTO_TRADE)return;try{const rows=await getRecoverableMt5Commands();let restored=0;for(const cmd of rows){if(!cmd?.id||mt5Exec.seen.has(cmd.id))continue;mt5Exec.seen.add(cmd.id);mt5Exec.queue.push(cmd);if(cmd.setupId&&cmd.timeframe&&cmd.action==='PLACE_LIMIT')mt5Exec.limits.set(limitKey(cmd.timeframe,cmd.setupId),{...cmd,status:'QUEUED',placeId:cmd.id});restored++}console.log('MT5 execution recovery restored='+restored)}catch(e){console.error('MT5 execution recovery failed:',e.message)}}
async function sendMt5Private(text,meta={}){if(!TELEGRAM_BOT_TOKEN||!TELEGRAM_CHAT_ID)return false;const started=Date.now();try{const resp=await fetch(\`https://api.telegram.org/bot\${TELEGRAM_BOT_TOKEN}/sendMessage\`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:TELEGRAM_CHAT_ID,text,disable_web_page_preview:true})});const apiMs=Date.now()-started;if(!resp.ok){console.error('Telegram PRIVATE MT5 send failed:',resp.status,await resp.text());return false}Object.assign(telegramMetrics,{lastSentAt:Date.now(),lastApiMs:apiMs,lastEvent:meta.event||'MT5_EXECUTION',lastTimeframe:meta.tf||null});return true}catch(e){console.error('Telegram PRIVATE MT5 error:',e.message);return false}}
function limitKey(tf,setupId){return \`\${tf}:\${setupId}\`}
function buildLimit(tf,s){const e=engines[tf],pip=Number(e.config.pipSize||0.1),entry=Number(s.plannedEntry),structuralSl=Number(s.structuralSl),bufferPips=Math.max(0,Number(e.config.slBufferPips||0)),bufferPrice=bufferPips*pip,sl=s.dir==='buy'?structuralSl-bufferPrice:structuralSl+bufferPrice,risk=Math.abs(entry-sl),rr=Array.isArray(e.config.rr)?e.config.rr:[1,2,3,4],tps=rr.map(r=>s.dir==='buy'?entry+risk*Number(r):entry-risk*Number(r)),p=tpProbabilityEstimate(s.quality||{},dxyContext(tf,s.dir),s.dir);return{setupId:String(s.id),symbol:e.config.symbol,timeframe:tf,side:String(s.dir).toUpperCase(),entry,sl,tp1:Number(tps[0]),tp2:Number(tps[1]),tp3:Number(tps[2]),tp4:Number(tps[3]),tp1Probability:p.tp1,tp2Probability:p.tp2,tp3Probability:p.tp3,tp4Probability:p.tp4,probabilityPriorityThreshold:80,pipSize:pip,slMoveTriggerPips:5,slMoveTo:'TP1',profitLockMode:'TP_PROBABILITY_CANDLE_CLOSE'}}
function enqueueMt5Limit(tf,s){if(!AUTO_TRADE||!s||s.status!=='pending')return;const key=limitKey(tf,s.id);if(mt5Exec.limits.has(key))return;const aiFilter=aiEntryFilterDecision(tf,s.dir);s.aiEntryFilter={...aiFilter,checkedAt:Date.now(),mode:'SHADOW_VALIDATE'};console.log('AI PRE-ENTRY SHADOW tf='+tf+' setup='+s.id+' side='+String(s.dir).toUpperCase()+' decision='+aiFilter.decision+' reason='+aiFilter.reason);const payload=buildLimit(tf,s);payload.aiEntryFilter=s.aiEntryFilter;if(![payload.entry,payload.sl,payload.tp1,payload.tp4].every(Number.isFinite))return;const id=\`place-\${tf}-\${s.id}\`;mt5Exec.limits.set(key,{...payload,status:'QUEUED',placeId:id,createdAt:Date.now()});if(mt5Exec.seen.has(id))return;mt5Exec.seen.add(id);const cmd={id,action:'PLACE_LIMIT',...payload,createdAt:Date.now()};mt5Exec.queue.push(cmd);void persistExec(cmd,'QUEUED');console.log(\`MT5 first-touch LIMIT queued id=\${id} tf=\${tf} side=\${payload.side} entry=\${payload.entry}\`)}
function enqueueMt5Cancel(tf,setupId,reason='invalidated'){if(!AUTO_TRADE||!setupId)return;const key=limitKey(tf,setupId),lim=mt5Exec.limits.get(key);if(!lim||['FILLED','CANCELLED','MISSED','REJECTED'].includes(String(lim.status)))return;const id=\`cancel-\${tf}-\${setupId}\`;if(mt5Exec.seen.has(id))return;mt5Exec.seen.add(id);lim.status='CANCEL_QUEUED';const cmd={id,action:'CANCEL_LIMIT',setupId:String(setupId),symbol:lim.symbol,timeframe:tf,side:lim.side,reason:String(reason),createdAt:Date.now()};mt5Exec.queue.push(cmd);void persistExec(cmd,'CANCEL_QUEUED');console.log(\`MT5 LIMIT cancel queued id=\${id} reason=\${reason}\`)}
function markMt5LimitTouched(tf,setupId){const lim=mt5Exec.limits.get(limitKey(tf,setupId));if(lim&&!['FILLED','CANCELLED'].includes(String(lim.status)))lim.status='TOUCHED_WEB'}
function syncAllPendingLimits(){if(!AUTO_TRADE)return;for(const tf of TFS)for(const s of engines[tf].setups)if(s.status==='pending')enqueueMt5Limit(tf,s)}
function dxyRecoveryStatus(){return{requiredBars:21,dxyBars:dxy.candles.length,xauBars:engines.M1.candles.length,ready:Boolean(dxy.ready&&dxy.candles.length>=21&&engines.M1.candles.length>=21)}}
`;
if(!source.includes('const mt5Exec='))source=source.replace("const mt5={lastSeen:null",autoExecPrelude+"\nconst mt5={lastSeen:null");

const oldDispatch="function dispatchTransitions(tf,beforeTrades,beforePending){const e=engines[tf];let transitions=0;for(const t of e.trades){const p=beforeTrades.get(t.id);if(!p){transitions++;void sendTelegram(entryMessage(tf,t),{event:'ENTRY',tf});continue}let highest=-1;for(let i=0;i<t.tpHits.length;i++)if(!p.tpHits[i]&&t.tpHits[i])highest=i;if(highest>=0){transitions++;void sendTelegram(tpMessage(tf,t,highest),{event:`TP${highest+1}`,tf});if(highest===3){transitions++;void sendTelegram(closedMessage(tf,t,'TP4'),{event:'SIGNAL_CLOSED_TP4',tf})}}if(p.status==='live'&&t.status==='closed'&&t.result==='SL'){transitions++;void sendTelegram(slMessage(tf,t),{event:'SL',tf});transitions++;void sendTelegram(closedMessage(tf,t,'SL'),{event:'SIGNAL_CLOSED_SL',tf})}}if(TELEGRAM_NOTIFY_PENDING)for(const s of e.setups)if(s.status==='pending'&&!beforePending.has(s.id)){transitions++;void sendTelegram(pendingMessage(tf,s),{event:'PENDING',tf})}return transitions}";
const newDispatch="function dispatchTransitions(tf,beforeTrades,beforePending){const e=engines[tf];let transitions=0;for(const t of e.trades){const p=beforeTrades.get(t.id);if(!p){transitions++;markMt5LimitTouched(tf,t.setupId);void sendTelegram(entryMessage(tf,t),{event:'ENTRY',tf});continue}let highest=-1;for(let i=0;i<t.tpHits.length;i++)if(!p.tpHits[i]&&t.tpHits[i])highest=i;if(highest>=0){transitions++;void sendTelegram(tpMessage(tf,t,highest),{event:`TP${highest+1}`,tf})}if(p.status==='live'&&t.status==='closed'&&t.result==='SL'){transitions++;void sendTelegram(slMessage(tf,t),{event:'SL',tf})}}const afterPending=new Set(e.setups.filter(s=>s.status==='pending').map(s=>s.id));for(const s of e.setups)if(s.status==='pending'&&!beforePending.has(s.id)){enqueueMt5Limit(tf,s);if(TELEGRAM_NOTIFY_PENDING){transitions++;void sendTelegram(pendingMessage(tf,s),{event:'PENDING',tf})}}for(const id of beforePending){if(afterPending.has(id))continue;const s=e.setups.find(x=>x.id===id);if(s?.status==='filled'){markMt5LimitTouched(tf,id);continue}enqueueMt5Cancel(tf,id,s?.status||'replaced')}return transitions}";
if(source.includes(oldDispatch))source=source.replace(oldDispatch,newDispatch);else if(!source.includes('function dispatchTransitions('))throw new Error('dispatchTransitions not found');

// Realtime Web AI uses MT5 sides: BUY touch on Ask, SELL touch on Bid.
const oldRealtime="function processRealtimeTick(price,time){let changed=false,transitions=0;for(const tf of TFS){const e=engines[tf],bt=tradeMap(e),bp=pendingSet(e),r=e.processTick({price,time});if(!r.changed)continue;changed=true;transitions+=dispatchTransitions(tf,bt,bp)}if(changed){mt5.lastRealtimeTransition=Date.now();scheduleDbSync()}return{changed,transitions}}";
const newRealtime="function processRealtimeTick(bid,ask,time){if(dbReady)void updateAiMarketPlans(Number.isFinite(Number(bid))?Number(bid):Number(ask),time).catch(e=>console.error('AI plan tracking failed:',e.message));let changed=false,transitions=0;for(const tf of TFS){const e=engines[tf],bt=tradeMap(e),bp=pendingSet(e),r=e.processTick({bid,ask,price:bid,time,context:{dxy:dxyContext(tf,'buy')}});if(!r.changed)continue;changed=true;transitions+=dispatchTransitions(tf,bt,bp)}if(changed){mt5.lastRealtimeTransition=Date.now();scheduleDbSync()}return{changed,transitions}}";
if(source.includes(oldRealtime))source=source.replace(oldRealtime,newRealtime);else if(source.includes('function processRealtimeTick(price,time)')){source=source.replace('function processRealtimeTick(price,time)','function processRealtimeTick(bid,ask,time)').replace("r=e.processTick({price,time})","r=e.processTick({bid,ask,price:bid,time,context:{dxy:dxyContext(tf,'buy')}})");}else if(!source.includes('function processRealtimeTick(bid,ask,time)'))throw new Error('Realtime processing function not found');
const oldTick="const price=Number.isFinite(Number(mt5.bid))?Number(mt5.bid):Number(mt5.ask),realtime=Number.isFinite(price)?processRealtimeTick(price,mt5.lastTick):{changed:false,transitions:0};";
const newTick="const bid=Number(mt5.bid),ask=Number(mt5.ask),realtime=(Number.isFinite(bid)||Number.isFinite(ask))?processRealtimeTick(bid,ask,mt5.lastTick):{changed:false,transitions:0};";
if(source.includes(oldTick))source=source.replace(oldTick,newTick);else if(!source.includes('processRealtimeTick(bid,ask,mt5.lastTick)'))throw new Error('MT5 tick bid/ask route patch marker not found');

// After every backfill/restart, re-arm currently valid pending setups as LIMIT orders.
const backfillNeedle="for(const c of cs)ingestOne(c.timeframe||tf,c,b.autoAggregate!==false,false);mt5.lastSeen=Date.now();await syncAllToDatabase();";
const backfillReplacement="for(const c of cs)ingestOne(c.timeframe||tf,c,b.autoAggregate!==false,false);mt5.lastSeen=Date.now();syncAllPendingLimits();await syncAllToDatabase();";
if(source.includes(backfillNeedle))source=source.replace(backfillNeedle,backfillReplacement);else if(!source.includes('syncAllPendingLimits();await syncAllToDatabase()'))throw new Error('Backfill LIMIT sync patch marker not found');

const autoExecRoutes=`
app.get('/api/mt5/dxy-recovery',(q,r)=>{if(!requireBridge(q,r))return;const x=dxyRecoveryStatus();r.json({ok:true,...x,needBackfill:!x.ready,recommendedBars:Math.max(60,x.requiredBars),message:x.ready?'DXY_READY':'SEND_DXY_M1_BACKFILL'});});
app.get('/api/mt5/commands',(q,r)=>{if(!requireBridge(q,r))return;mt5Exec.lastPoll=Date.now();r.json({ok:true,autoTrade:AUTO_TRADE,mode:'FIRST_TOUCH_LIMIT_V2_2',commands:[],upgradeRequired:true});});
app.get('/api/mt5/limit-commands',(q,r)=>{if(!requireBridge(q,r))return;mt5Exec.lastPoll=Date.now();if(!AUTO_TRADE)return r.json({ok:true,autoTrade:false,mode:'FIRST_TOUCH_LIMIT_V2_2',commands:[]});const seen=new Set(),commands=[];for(const cmd of mt5Exec.queue){const key=String(cmd?.setupId||cmd?.id||'');if(!key||seen.has(key))continue;seen.add(key);let lim=null;if(cmd?.setupId&&cmd?.timeframe)lim=mt5Exec.limits.get(limitKey(cmd.timeframe,cmd.setupId))||null;if(!lim){for(const x of mt5Exec.limits.values()){if(String(x.placeId)===String(cmd.id)){lim=x;break}}}const st=String(lim?.status||'').toUpperCase();if(['PLACED','EXECUTED','FILLED','MISSED','FAILED','REJECTED','CANCELLED'].includes(st))continue;commands.push(cmd);if(commands.length>=20)break}r.json({ok:true,autoTrade:true,mode:'FIRST_TOUCH_LIMIT_V2_2',commands});});
app.post(['/api/mt5/commands/ack','/api/mt5/limit-commands/ack'],(q,r)=>{if(!requireBridge(q,r))return;const b=q.body||{},id=String(b.id||''),status=String(b.status||'UNKNOWN').toUpperCase(),ticket=String(b.ticket||'-');if(!id)return r.status(400).json({ok:false,error:'id required'});const ackKey=\`\${id}|\${status}|\${ticket}\`;if(mt5Exec.acked.has(ackKey))return r.json({ok:true,duplicate:true});const idx=mt5Exec.queue.findIndex(x=>x.id===id),cmd=idx>=0?mt5Exec.queue[idx]:null;if(idx>=0)mt5Exec.queue.splice(idx,1);mt5Exec.acked.set(ackKey,{...b,ackedAt:Date.now()});if(mt5Exec.acked.size>1000)mt5Exec.acked.delete(mt5Exec.acked.keys().next().value);mt5Exec.lastAck=Date.now();let tf=String(b.timeframe||cmd?.timeframe||'-'),setupId=String(b.setupId||cmd?.setupId||''),side=String(b.side||cmd?.side||'-');const detail=String(b.detail||'-');let lim=null;if(setupId&&tf!=='-')lim=mt5Exec.limits.get(limitKey(tf,setupId))||null;if(!lim){for(const [lk,x] of mt5Exec.limits.entries()){if(String(x.placeId)===id){lim=x;const cut=lk.indexOf(':');if(tf==='-')tf=lk.slice(0,cut);if(!setupId)setupId=lk.slice(cut+1);if(side==='-')side=String(x.side||'-');break}}}void persistAck(id,status,ticket,detail);if(lim){if(status==='PLACED'){lim.status='PLACED';lim.orderTicket=ticket}else if(status==='EXECUTED'){lim.status='FILLED';lim.positionTicket=ticket;lim.fillPrice=Number(b.fillPrice)}else if(status==='CANCELLED'){lim.status='CANCELLED'}else if(['FAILED','REJECTED','MISSED'].includes(status)){lim.status=status;lim.error=detail}}console.log(\`MT5 LIMIT ack id=\${id} status=\${status} ticket=\${ticket} setup=\${setupId||'-'}\`);const planned=Number(b.entry??cmd?.entry??lim?.entry),fill=Number(b.fillPrice),diffPips=Number.isFinite(fill)&&Number.isFinite(planned)&&Number(lim?.pipSize||cmd?.pipSize)>0?Math.abs(fill-planned)/Number(lim?.pipSize||cmd?.pipSize):null;if(status==='EXECUTED'){void sendMt5Private(\`✅ MT5 LIMIT FILLED\\nSymbol: \${cmd?.symbol||lim?.symbol||'XAUUSD'}\\nTF: \${tf}\\nSide: \${side}\\nTicket: \${ticket}\\nEntry AI/LIMIT: \${Number.isFinite(planned)?planned:'-'}\\nFill: \${Number.isFinite(fill)?fill:'-'}\\nSelisih: \${diffPips===null?'-':diffPips.toFixed(1)+' pips'}\\nSL: \${lim?.sl??cmd?.sl??'-'}\\nTP1: \${lim?.tp1??cmd?.tp1??'-'}\\nTP4: \${lim?.tp4??cmd?.tp4??'-'}\\nMode: FIRST TOUCH LIMIT\\nManagement: TP1 + 5 pips → SL ke TP1\\nSetup: \${setupId||'-'}\`,{event:'MT5_LIMIT_FILLED',tf})}else if(['FAILED','REJECTED','MISSED'].includes(status)){void sendMt5Private(\`❌ MT5 LIMIT \${status}\\nSymbol: \${cmd?.symbol||lim?.symbol||'XAUUSD'}\\nTF: \${tf}\\nSide: \${side}\\nEntry LIMIT: \${Number.isFinite(planned)?planned:'-'}\\nReason: \${detail}\\nSetup: \${setupId||'-'}\`,{event:'MT5_LIMIT_'+status,tf})}r.json({ok:true})});
app.get('/api/mt5/execution-audit',async(q,r)=>{if(!requireBridge(q,r))return;try{r.json({ok:true,rows:await getMt5ExecutionAudit(q.query.limit||200)})}catch(e){r.status(500).json({ok:false,error:e.message})}});
app.get('/api/mt5/auto-status',(q,r)=>{if(!requireBridge(q,r))return;const states={};for(const x of mt5Exec.limits.values())states[x.status]=(states[x.status]||0)+1;r.json({ok:true,autoTrade:AUTO_TRADE,mode:'FIRST_TOUCH_LIMIT_V2_2',queued:mt5Exec.queue.length,limits:states,acked:mt5Exec.acked.size,lastPoll:mt5Exec.lastPoll,lastAck:mt5Exec.lastAck,management:'MT5 only: TP1 + 5 pips => SL moves to TP1'});});
`;
if(!source.includes("app.get('/api/mt5/commands'"))source=source.replace("app.get('/api/health'",autoExecRoutes+"\napp.get('/api/health'");
fs.writeFileSync(serverPath,source,'utf8');
await import('./server.js');
setTimeout(()=>{recoverMt5ExecutionQueue().catch(e=>console.error('MT5 recovery startup failed:',e.message))},2500);
