const clone = (v) => JSON.parse(JSON.stringify(v));

export const defaultConfig = {
  symbol: 'XAUUSD', timeframe: 'M1', atrPeriod: 14, displacementAtr: 1.5, pivotStrength: 4,
  pipSize: 0.1, maxSwingSlPips: 50, slBufferPips: 5, fvgEntryMode: 'first_touch',
  rr: [1, 2, 3, 4], maxObFvgBars: 6, maxFreshAgeBars: 300, setupExpiryBars: 100, qualityGateMode: 'shadow', qualityAutoMin: 75, qualityShadowMin: 55,
};

const tr=(a,b)=>Math.max(a.high-a.low,Math.abs(a.high-b.close),Math.abs(a.low-b.close));
const normTime=(v)=>{const n=Number(v??Date.now());return n<1e12?n*1000:n};
const tradeOutcome=(t)=>t.tpHits?.[0]?'WIN':(t.status==='closed'&&t.result==='SL'?'LOSS':'OPEN');
function atr(candles,period){if(candles.length<period+1)return null;let sum=0;for(let i=candles.length-period;i<candles.length;i++)sum+=tr(candles[i],candles[i-1]);return sum/period}
function plannedEntry(dir,top,bottom,mode){if(mode==='top')return top;if(mode==='bottom')return bottom;if(mode==='mid')return(top+bottom)/2;return dir==='buy'?top:bottom}
function targets(dir,entry,sl,rr){const risk=Math.abs(entry-sl);return rr.map(r=>dir==='buy'?entry+risk*r:entry-risk*r)}
function ema(values,period){if(!values.length)return null;const a=2/(period+1);let x=values[0];for(let i=1;i<values.length;i++)x=values[i]*a+x*(1-a);return x}
function qualityAssessment(candles,dir,ob,fvg,structuralSlPips,cfg){
  const closes=candles.slice(-60).map(x=>x.close),e20=ema(closes.slice(-40),20),e50=ema(closes,50),last=closes.at(-1);
  const regime=e20!=null&&e50!=null?(e20>e50&&last>=e20?'bullish':e20<e50&&last<=e20?'bearish':'neutral'):'unknown';
  const aligned=(dir==='buy'&&regime==='bullish')||(dir==='sell'&&regime==='bearish');
  const neutral=regime==='neutral'||regime==='unknown';
  const obAge=Math.max(0,candles.length-1-ob.born),fvgSizePips=Math.abs(fvg.top-fvg.bottom)/cfg.pipSize;
  let score=0; score+=aligned?25:neutral?12:0; score+=ob.fresh?15:0; score+=fvg.fresh?15:0; score+=obAge<=cfg.maxObFvgBars+1?15:5;
  score+=fvgSizePips>=2?10:5; score+=structuralSlPips<=30?15:structuralSlPips<=cfg.maxSwingSlPips?8:0; score+=5;
  score=Math.max(0,Math.min(100,Math.round(score)));
  const grade=score>=Number(cfg.qualityAutoMin||75)?'A':score>=Number(cfg.qualityShadowMin||55)?'B':'C';
  return{mode:String(cfg.qualityGateMode||'shadow').toUpperCase(),score,grade,regime,regimeAligned:aligned,ema20:e20,ema50:e50,obAgeBars:obAge,fvgSizePips:+fvgSizePips.toFixed(1),reasons:[aligned?'REGIME_ALIGNED':neutral?'REGIME_NEUTRAL':'REGIME_COUNTER',ob.fresh?'FRESH_OB':'STALE_OB',fvg.fresh?'FRESH_FVG':'STALE_FVG',structuralSlPips<=30?'SL_EFFICIENT':'SL_WIDE']};
}

export function tpProbabilityEstimate(quality={},dxy=null,dir=''){const s=Math.max(0,Math.min(100,Number(quality.score||0)));const aligned=quality.regimeAligned===true,neutral=['neutral','unknown'].includes(String(quality.regime||''));const rawDxyScore=Number(dxy?.score||0),dxyScore=dir==='sell'?-rawDxyScore:rawDxyScore,adj=Number.isFinite(dxyScore)?Math.max(-15,Math.min(15,dxyScore)):0;const p1=Math.round(Math.max(20,Math.min(95,42+s*.45+(aligned?8:neutral?2:-6)+adj)));const p2=Math.round(Math.max(15,Math.min(p1,p1-12+Math.round(adj*.25))));const p3=Math.round(Math.max(10,Math.min(p2,p2-13+Math.round(adj*.2))));const p4=Math.round(Math.max(5,Math.min(p3,p3-14+Math.round(adj*.15))));return{mode:'SHADOW',method:dxy?.ready?'QUALITY_GATE_DXY_V2':'QUALITY_GATE_HEURISTIC_V1',tp1:p1,tp2:p2,tp3:p3,tp4:p4,confidence:Math.round(Math.max(30,Math.min(95,35+s*.5+Math.abs(adj)*.3))),dxy:dxy?.ready?{symbol:dxy.symbol,trend:dxy.trend,correlation:dxy.correlation,score:adj,alignment:adj>0?'SUPPORT':adj<0?'CONFLICT':'NEUTRAL'}:null}}
export class StrategyEngine {
  constructor(config={}){this.config={...defaultConfig,...config};this.reset()}
  reset(){this.candles=[];this.obs=[];this.fvgs=[];this.setups=[];this.trades=[];this.skipped=0;this.lastSignal=null;this.lastRealtimeTick=null}
  updateConfig(patch={}){const safePatch={...patch};if(safePatch.rr&&!Array.isArray(safePatch.rr))delete safePatch.rr;this.config={...this.config,...safePatch};return clone(this.config)}
  ingest(candle){const c={time:normTime(candle.time),open:Number(candle.open),high:Number(candle.high),low:Number(candle.low),close:Number(candle.close),volume:Number(candle.volume??0)};if(![c.open,c.high,c.low,c.close].every(Number.isFinite))throw new Error('Invalid OHLC candle');this.candles.push(c);if(this.candles.length>5000)this.candles.shift();const i=this.candles.length-1;this.detectOb(i);this.detectFvg(i);this.refreshFreshness(i);this.matchSetups(i);this.processSetups(i);this.processTrades(i);return this.snapshot()}
  detectOb(i){if(i<2)return;const a=atr(this.candles.slice(0,i+1),this.config.atrPeriod);if(!a)return;const c=this.candles[i],p=this.candles[i-1];const bullDisp=c.close>c.open&&c.close-c.open>=a*this.config.displacementAtr;const bearDisp=c.close<c.open&&c.open-c.close>=a*this.config.displacementAtr;if(bullDisp&&p.close<p.open)this.obs.push({id:`ob-${i}-b`,dir:'buy',top:p.high,bottom:p.low,sl:p.low,born:i-1,bornTime:p.time,fresh:true,paired:false});if(bearDisp&&p.close>p.open)this.obs.push({id:`ob-${i}-s`,dir:'sell',top:p.high,bottom:p.low,sl:p.high,born:i-1,bornTime:p.time,fresh:true,paired:false})}
  detectFvg(i){if(i<2)return;const c=this.candles[i],a=this.candles[i-2];if(c.low>a.high)this.fvgs.push({id:`fvg-${i}-b`,dir:'buy',top:c.low,bottom:a.high,born:i,bornTime:c.time,fresh:true});if(c.high<a.low)this.fvgs.push({id:`fvg-${i}-s`,dir:'sell',top:a.low,bottom:c.high,born:i,bornTime:c.time,fresh:true})}
  refreshFreshness(i){const c=this.candles[i];for(const ob of this.obs){if(!ob.fresh||i<=ob.born+1)continue;if(i-ob.born>this.config.maxFreshAgeBars||(c.high>=ob.bottom&&c.low<=ob.top))ob.fresh=false}for(const f of this.fvgs){if(!f.fresh||i<=f.born)continue;if(i-f.born>this.config.maxFreshAgeBars||(c.high>=f.bottom&&c.low<=f.top))f.fresh=false}this.obs=this.obs.slice(-100);this.fvgs=this.fvgs.slice(-150)}
  matchSetups(i){const freshNewFvgs=this.fvgs.filter(f=>f.born===i);for(const fvg of freshNewFvgs){const ob=[...this.obs].reverse().find(o=>o.dir===fvg.dir&&o.fresh&&!o.paired&&i-o.born>=1&&i-o.born<=this.config.maxObFvgBars+1);if(!ob)continue;const entry=plannedEntry(fvg.dir,fvg.top,fvg.bottom,this.config.fvgEntryMode);const structuralSlPips=Math.abs(entry-ob.sl)/this.config.pipSize;ob.paired=true;if(structuralSlPips>this.config.maxSwingSlPips){this.skipped++;continue}this.setups=this.setups.filter(s=>s.dir!==fvg.dir||s.status!=='pending');const quality=qualityAssessment(this.candles,fvg.dir,ob,fvg,structuralSlPips,this.config);this.setups.push({id:`setup-${i}-${fvg.dir}`,dir:fvg.dir,obId:ob.id,fvgId:fvg.id,fvgTop:fvg.top,fvgBottom:fvg.bottom,structuralSl:ob.sl,structuralSlPips,plannedEntry:entry,born:i,bornTime:this.candles[i].time,status:'pending',validated:true,quality})}}
  openTradeFromSetup(s,i,time,source='candle',context={}){if(s.status!=='pending')return{changed:false,opened:false};const entry=plannedEntry(s.dir,s.fvgTop,s.fvgBottom,this.config.fvgEntryMode);s.plannedEntry=entry;const structuralSl=s.structuralSl;const structuralSlPips=Math.abs(entry-structuralSl)/this.config.pipSize;if(structuralSlPips>this.config.maxSwingSlPips){s.status='skipped';s.skipReason=`Swing SL ${structuralSlPips.toFixed(1)} pips > ${this.config.maxSwingSlPips}`;this.skipped++;return{changed:true,opened:false}}const bufferPips=Math.max(0,Number(this.config.slBufferPips??0));const bufferPrice=bufferPips*this.config.pipSize;const sl=s.dir==='buy'?structuralSl-bufferPrice:structuralSl+bufferPrice;const slPips=Math.abs(entry-sl)/this.config.pipSize;const tps=targets(s.dir,entry,sl,this.config.rr);const openedTime=normTime(time);const trade={id:`trade-${this.config.timeframe}-${s.id}`,setupId:s.id,timeframe:this.config.timeframe,dir:s.dir,entry,structuralSl,structuralSlPips,slBufferPips:bufferPips,sl,slPips,tps,quality:s.quality?clone(s.quality):null,tpProbability:tpProbabilityEstimate(s.quality||{},context?.dxy,s.dir),opened:i,openedTime,openedSource:source,entryConfirmed:true,status:'live',tpHits:[false,false,false,false],result:null,armedFrom:i+1,realtimeArmedAfter:openedTime};this.trades.push(trade);s.status='filled';s.filledTime=openedTime;s.filledSource=source;this.lastSignal={...trade,symbol:this.config.symbol,timeframe:this.config.timeframe,time:openedTime};return{changed:true,opened:true,trade}}
  processSetups(i){const c=this.candles[i];for(const s of this.setups){if(s.status!=='pending'||i<=s.born)continue;if(i-s.born>this.config.setupExpiryBars){s.status='expired';continue}const entry=plannedEntry(s.dir,s.fvgTop,s.fvgBottom,this.config.fvgEntryMode);s.plannedEntry=entry;if(c.high>=entry&&c.low<=entry)this.openTradeFromSetup(s,i,c.time,'candle',{})}}
  processTrades(i){const c=this.candles[i];for(const t of this.trades){if(t.status!=='live'||!t.entryConfirmed)continue;if(i<(t.armedFrom??t.opened+1))continue;const slHit=t.dir==='buy'?c.low<=t.sl:c.high>=t.sl;if(slHit){t.status='closed';t.result='SL';t.closed=i;t.closedTime=c.time;continue}t.tps.forEach((tp,n)=>{if(!t.tpHits[n]&&(t.dir==='buy'?c.high>=tp:c.low<=tp))t.tpHits[n]=true});if(t.tpHits[3]){t.status='closed';t.result='TP4';t.closed=i;t.closedTime=c.time}}this.trades=this.trades.slice(-500)}
  processTick(tick){const bid=Number(tick?.bid??tick?.price),ask=Number(tick?.ask??tick?.price),fallback=Number(tick?.price);const time=normTime(tick?.time??Date.now());if(!Number.isFinite(bid)&&!Number.isFinite(ask)&&!Number.isFinite(fallback))throw new Error('Invalid realtime tick price');const safeBid=Number.isFinite(bid)?bid:(Number.isFinite(fallback)?fallback:ask);const safeAsk=Number.isFinite(ask)?ask:(Number.isFinite(fallback)?fallback:bid);this.lastRealtimeTick={price:safeBid,bid:safeBid,ask:safeAsk,time};let changed=false;const i=Math.max(0,this.candles.length-1);for(const s of this.setups){if(s.status!=='pending')continue;if(i-s.born>this.config.setupExpiryBars){s.status='expired';changed=true;continue}const entry=plannedEntry(s.dir,s.fvgTop,s.fvgBottom,this.config.fvgEntryMode);s.plannedEntry=entry;const entryTouched=s.dir==='buy'?safeAsk<=entry:safeBid>=entry;if(!entryTouched)continue;const opened=this.openTradeFromSetup(s,i,time,'tick',tick?.context||{});changed=changed||opened.changed}for(const t of this.trades){if(t.status!=='live'||!t.entryConfirmed)continue;if(time<=Number(t.realtimeArmedAfter??t.openedTime??0))continue;const exitPrice=t.dir==='buy'?safeBid:safeAsk;const slHit=t.dir==='buy'?exitPrice<=t.sl:exitPrice>=t.sl;if(slHit){t.status='closed';t.result='SL';t.closed=i;t.closedTime=time;t.closedSource='tick';changed=true;continue}for(let n=0;n<t.tps.length;n++){const hit=t.dir==='buy'?exitPrice>=t.tps[n]:exitPrice<=t.tps[n];if(!t.tpHits[n]&&hit){t.tpHits[n]=true;changed=true}}if(t.tpHits[3]){t.status='closed';t.result='TP4';t.closed=i;t.closedTime=time;t.closedSource='tick';changed=true}}this.trades=this.trades.slice(-500);return{changed,price:safeBid,bid:safeBid,ask:safeAsk,time}}
  stats(){const all=this.trades.filter(t=>t.entryConfirmed===true);const primaryWins=all.filter(t=>t.tpHits[0]).length;const primaryLosses=all.filter(t=>!t.tpHits[0]&&t.status==='closed'&&t.result==='SL').length;const primaryResolved=primaryWins+primaryLosses;const primary={wins:primaryWins,losses:primaryLosses,resolved:primaryResolved,winrate:primaryResolved?+(primaryWins/primaryResolved*100).toFixed(1):0};const wr=[0,1,2,3].map(n=>{const wins=all.filter(t=>t.tpHits[n]).length;const losses=all.filter(t=>!t.tpHits[n]&&t.status==='closed'&&t.result==='SL').length;const resolved=wins+losses;return{target:n+1,wins,losses,resolved,winrate:resolved?+(wins/resolved*100).toFixed(1):0}});return{total:all.length,confirmedEntries:all.length,live:all.filter(t=>t.status==='live').length,skipped:this.skipped,primary,winrates:wr}}
  snapshot(){return{config:clone(this.config),price:this.lastRealtimeTick?.price??this.candles.at(-1)?.close??null,lastCandleTime:this.candles.at(-1)?.time??null,lastRealtimeTick:this.lastRealtimeTick?clone(this.lastRealtimeTick):null,hybridRealtime:true,freshOB:this.obs.filter(x=>x.fresh),freshFVG:this.fvgs.filter(x=>x.fresh),pending:this.setups.filter(x=>x.status==='pending'),liveTrades:this.trades.filter(x=>x.entryConfirmed===true&&x.status==='live'),history:this.trades.filter(x=>x.entryConfirmed===true).slice(-100).reverse().map(t=>({...t,outcome:tradeOutcome(t)})),stats:this.stats(),lastSignal:this.lastSignal}}
}
